#1172 skip

diff --git a/src/docker/Dockerfile b/src/docker/Dockerfile
--- a/src/docker/Dockerfile
+++ b/src/docker/Dockerfile
@@ -67,7 +67,7 @@ RUN apt-get update && apt-get install -y libmagic-dev=1:5.14-2ubuntu3.3 \
     zlib1g-dev=1:1.2.8.dfsg-1ubuntu1
 RUN apt-add-repository -y ppa:rael-gc/rvm
 RUN apt-get update
-RUN apt-get install -y rvm
+RUN apt-get install -y rvm || echo 'failed?'
 RUN source /usr/share/rvm/scripts/rvm
 RUN rvm install 2.3.3
 RUN gem update && gem install nokogiri:1.6.7.2 && gem install bundler:1.11.2
